server:
  port: 8082
spring:
#  邮件配置
  mail:
#    邮件服务器地址
    host: smtp.126.com
#    协议
    protocol: smtp
#    编码格式
    default-encoding: utf-8
#    授权码（在邮箱开通服务时获取）
    password: FZJMAQQHEVLQCKMQ
#    发送者邮箱地址
    username: ym13255653842@126.com
#    端口（不同邮箱端口号不同）
    port: 25
  rabbitmq:
    username: guest
    password: guest
    host: 192.168.121.11
    port: 5672